// src/constants/permissions.ts
export enum Permission {
  TENANT_READ = "TENANT_READ",
  TENANT_CREATE = "TENANT_CREATE",
  TENANT_UPDATE = "TENANT_UPDATE",
  TENANT_DELETE = "TENANT_DELETE",

  PROPERTY_READ = "PROPERTY_READ",
  PROPERTY_MANAGE = "PROPERTY_MANAGE",

  PAYMENT_READ = "PAYMENT_READ",
  PAYMENT_COLLECT = "PAYMENT_COLLECT",

  USER_MANAGE = "USER_MANAGE",
  POLICY_READ = "POLICY_READ",
  POLICY_WRITE = "POLICY_WRITE",
  POLICY_APPROVE = "POLICY_APPROVE",
  POLICY_ADMIN = "POLICY_ADMIN"
}
